CREATE TABLE IF NOT EXISTS message_batches (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    public_id VARCHAR(48) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'queued',
    idempotency_key CHAR(64) NOT NULL,
    project_id VARCHAR(120) NULL,
    project_name VARCHAR(160) NULL,
    recipient_mode VARCHAR(32) NOT NULL DEFAULT 'all',
    message_kind VARCHAR(32) NOT NULL DEFAULT 'manual',
    send_notification TINYINT(1) NOT NULL DEFAULT 1,
    send_email TINYINT(1) NOT NULL DEFAULT 1,
    smtp_profile_key CHAR(64) NULL,
    payload_hash CHAR(64) NOT NULL,
    scene_hash CHAR(64) NULL,
    scene_version VARCHAR(32) NULL,
    normalizer_version VARCHAR(32) NULL,
    rate_limit_per_minute INT UNSIGNED NULL,
    total_jobs INT UNSIGNED NOT NULL DEFAULT 0,
    pending_jobs INT UNSIGNED NOT NULL DEFAULT 0,
    reserved_jobs INT UNSIGNED NOT NULL DEFAULT 0,
    processing_jobs INT UNSIGNED NOT NULL DEFAULT 0,
    retry_jobs INT UNSIGNED NOT NULL DEFAULT 0,
    sent_jobs INT UNSIGNED NOT NULL DEFAULT 0,
    failed_jobs INT UNSIGNED NOT NULL DEFAULT 0,
    cancelled_jobs INT UNSIGNED NOT NULL DEFAULT 0,
    last_error_excerpt VARCHAR(255) NULL,
    payload_snapshot_json LONGTEXT NOT NULL,
    scene_snapshot_json LONGTEXT NULL,
    editor_layers_snapshot_json LONGTEXT NULL,
    smtp_profile_snapshot_json LONGTEXT NULL,
    created_by INT UNSIGNED NULL,
    queued_at DATETIME NOT NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY ux_message_batches_public_id (public_id),
    UNIQUE KEY ux_message_batches_idempotency_key (idempotency_key),
    KEY idx_message_batches_status_queued (status, queued_at),
    KEY idx_message_batches_created_by (created_by),
    CONSTRAINT fk_message_batches_admin
        FOREIGN KEY (created_by) REFERENCES admins(id)
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS message_batch_jobs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    batch_id BIGINT UNSIGNED NOT NULL,
    public_id VARCHAR(48) NOT NULL,
    recipient_key CHAR(64) NOT NULL,
    dedupe_key CHAR(64) NOT NULL,
    customer_id INT UNSIGNED NULL,
    customer_email VARCHAR(160) NULL,
    send_notification TINYINT(1) NOT NULL DEFAULT 1,
    send_email TINYINT(1) NOT NULL DEFAULT 1,
    notification_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    email_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts INT UNSIGNED NOT NULL DEFAULT 4,
    available_at DATETIME NOT NULL,
    reserved_at DATETIME NULL,
    processing_at DATETIME NULL,
    heartbeat_at DATETIME NULL,
    lease_until DATETIME NULL,
    worker_id VARCHAR(120) NULL,
    reservation_token CHAR(32) NULL,
    subject_snapshot VARCHAR(255) NOT NULL,
    customer_snapshot_json LONGTEXT NOT NULL,
    token_snapshot_json LONGTEXT NOT NULL,
    content_snapshot_json LONGTEXT NOT NULL,
    scene_hash CHAR(64) NULL,
    scene_version VARCHAR(32) NULL,
    normalizer_version VARCHAR(32) NULL,
    render_cache_key CHAR(64) NULL,
    render_path VARCHAR(255) NULL,
    last_stage VARCHAR(64) NULL,
    last_error_class VARCHAR(32) NULL,
    last_error_code VARCHAR(64) NULL,
    last_error_excerpt VARCHAR(255) NULL,
    last_error_detail LONGTEXT NULL,
    notification_sent_at DATETIME NULL,
    email_sent_at DATETIME NULL,
    finished_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY ux_message_batch_jobs_public_id (public_id),
    UNIQUE KEY ux_message_batch_jobs_dedupe_key (dedupe_key),
    UNIQUE KEY ux_message_batch_jobs_batch_recipient (batch_id, recipient_key),
    KEY idx_message_batch_jobs_dispatch (status, available_at, id),
    KEY idx_message_batch_jobs_lease (status, lease_until),
    KEY idx_message_batch_jobs_worker (worker_id, reservation_token),
    KEY idx_message_batch_jobs_batch_status (batch_id, status),
    KEY idx_message_batch_jobs_customer (customer_id),
    CONSTRAINT fk_message_batch_jobs_batch
        FOREIGN KEY (batch_id) REFERENCES message_batches(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_message_batch_jobs_customer
        FOREIGN KEY (customer_id) REFERENCES clientes(id)
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS message_send_log (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    batch_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NULL,
    attempt_number INT UNSIGNED NOT NULL DEFAULT 0,
    channel VARCHAR(32) NOT NULL DEFAULT 'job',
    stage VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    worker_id VARCHAR(120) NULL,
    error_class VARCHAR(32) NULL,
    error_code VARCHAR(64) NULL,
    summary VARCHAR(255) NULL,
    details_json LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_message_send_log_batch_created (batch_id, created_at),
    KEY idx_message_send_log_job_created (job_id, created_at),
    KEY idx_message_send_log_status_created (status, created_at),
    CONSTRAINT fk_message_send_log_batch
        FOREIGN KEY (batch_id) REFERENCES message_batches(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_message_send_log_job
        FOREIGN KEY (job_id) REFERENCES message_batch_jobs(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
